Repository thepracticaldev/DEV-ios, pull requests merged in 2018-12, with the labels that each got.

#105 Swiftlint config and linter corrections with minor improvements.
  .swiftlint.yml
  DEV-Simple/AppDelegate.swift
  DEV-Simple/BrowserViewController.swift
  DEV-Simple/ViewController.swift
  DEV-SimpleTests/ViewControllerTests.swift
Labels: PR: reviewed-changes-requested

#107 Adding CFBundleURLTypes from previous project
  DEV-Simple/Info.plist
Labels: PR: reviewed-approved

#110 Feature/haptic feedback
  DEV-Simple.xcodeproj/project.pbxproj
  DEV-Simple/ViewController.swift
Labels: PR: unreviewed

#109 Network Reachability
  Cartfile
  Cartfile.resolved
  DEV-Simple.xcodeproj/project.pbxproj
  DEV-Simple/AppDelegate.swift
  DEV-Simple/NetworkReachability.swift
  DEV-Simple/ViewController.swift
Labels: PR: reviewed-approved

#111 Bump version number
  DEV-Simple.xcodeproj/project.pbxproj
  DEV-Simple/Info.plist
Labels: PR: unreviewed

#112 Feature/iPad support
  DEV-Simple.xcodeproj/project.pbxproj
  DEV-Simple/Base.lproj/Main.storyboard
  DEV-Simple/ViewController.swift
Labels: PR: unreviewed
